### PR TITLE
Integer sloops and other improvements

### PR DESCRIPTION
**Pull request by SpexGuy**
This PR has four commits, because the changes depend on each other, but they could be detangled if you only want some of them.

## [Avoid fractional somersloops](https://github.com/Zistack/Satisfactory-Optimizer/commit/06055b804263cff3014d4f8a766819440ad30e91)

Turns out, scipy has limited support for variables which must be integers via the `integrality` parameter. This feature can be a performance hog if there are too many integer constraints, but I didn't notice much difference if integer values were only used for somersloops. I experimented with using integer constraints for machine counts as well, but that created significant performance issues so I backed it out.

## [Use integer machines, report underclocking precisely](https://github.com/Zistack/Satisfactory-Optimizer/pull/7/commits/fb8fe87e749766dbd4409dfb6d249359483fae81)

Using integer constraints for machine counts inside the optimizer is too expensive, but we can at least report integers to the user. Optimizing for minimum machines won't quite be optimal, but it should be close.
For the model to still be useful with integer machine counts, we also need to give underclocking instructions.
This commit specifies that in two ways:
`underclock_one` reports the amount you need to underclock the last machine, assuming all other machines have the base overclock value.
`underclock_uniform` reports an underclock amount that you can set in every machine, so that the total production is correct. Ideally this saves power over the underclock_one strategy due to the exponential curve. However, in large builds, this tends to end up very close to 1 and precision is lost.
However, with multiple active Corners, these values become unhelpful. So this commit solves that too. When multiple Corners are active at the same time, the report gives a "configurations" array. Each entry has a smaller number of machines, and its own clocking and sloop instructions. Some examples from the_big_cheese:
```js
        // All machines overclocked to 2.5
        "Extract Pure Oil": {
            "machine_count": "8",
            "power_consumption": "1074.479",
            "overclock_setting": "2.500000",
            "outputs": {
                "Crude Oil": "4800.000"
            }
        },

        // One machine, underclocked
        // Sink recipes are admittedly treated a bit strangely by this system
        "Sink Plutonium Fuel Rod": {
            "machine_count": "1",
            "power_consumption": "0.315",
            "overclock_setting": "0.010500",
            "inputs": {
                "Plutonium Fuel Rod": "12.600"
            },
            "outputs": {
                "Awesome Sink Point": "1930118.400"
            }
        },

        // 1.0 base underclock with slight adjustments
        "Electric Motor": {
            "machine_count": "65",
            "power_consumption": "971.667",
            "underclock_one": "0.777778",
            "underclock_uniform": "0.996581",
            "inputs": {
                "Electromagnetic Control Rod": "242.917",
                "Rotor": "485.833"
            },
            "outputs": {
                "Motor": "485.833"
            }
        },
        
        // Multiple corners simultaneously active
        "AI Expansion Server": {
            "machine_count": "18",
            "power_consumption": "53730.470",
            "configurations": [
                {
                    "machine_count": "14",
                    "power_consumption": "13437.500",
                    "underclock_one": "0.437500",
                    "underclock_uniform": "0.959821"
                },
                {
                    "machine_count": "3",
                    "power_consumption": "40292.970",
                    "overclock_setting": "2.500000",
                    "somersloops_slotted": "12"
                }
            ],
            "inputs": {
                "Magnetic Field Generator": "83.750",
                "Neural-Quantum Processor": "83.750",
                "Superposition Oscillator": "83.750",
                "Excited Photonic Matter": "2093.750"
            },
            "outputs": {
                "AI Expansion Server": "113.750",
                "Dark Matter Residue": "2843.750"
            }
        },

```

This commit should address #4

## [Add producers and consumers to items](https://github.com/Zistack/Satisfactory-Optimizer/pull/7/commits/c0c68b1d1b47191218dcbb0de0d2bbc09aa0ae60)

This commit adds `produced_by` and `consumed_by` fields to the `items` dictionary, which list the recipes that produce/consume each item and the amounts needed for each. I find these fields really useful for getting a quick feel for which alternates the solver is choosing to use.

## [Report more power statistics](https://github.com/Zistack/Satisfactory-Optimizer/pull/7/commits/c3e4238627bee7beb194b21c2bfe5b2d875c2a50)

This commit adds a few more power statistics, so you can see the raw power produced, the effect of augmentation, and the raw amount consumed. To avoid clutter, these new stats are only added to the report if the factory produces power.

### CODE REVIEW

**Comment by Zistack** [comment]
OK, I didn't know about integrality.  That's cool for sloops, and probably better than the solution I was working on.

I'll need to take a closer look at this later - there are some quirks about how the solver likes to distribute somersloops when overclocking is involved.  Generally, you'll want to split your machines into two sets when you do that, because the solver will often overclock slooped machines more than non-slooped machines even within the same recipe, and simply spreading out your sloops and clocking everything the same typically won't result in an equivalent configuration.

Also, it shouldn't be possible to adjust the clock speed of sink recipes at all.  I'll have to look into that.

**Comment by Zistack** [comment]
Looking at the first commit, primarily, I think I want to approach this in a somewhat different way.  The integrality stuff for scipy is good, but my corner infrastructure was designed to be extended in a different way than what you have done.  This will probably affect how reporting should be done as well.

If I could merge only pieces of your changes, I would.  I am not exactly a git(hub) master, though, and I'm not even sure that it is possible to do this.

**Comment by Zistack** [comment]
Question: I had originally imagined that choosing between 'underclock one' and 'underclock uniform' would be done with a command-line switch as a global option for the solver on all recipes.  You implemented it as a per-recipe configuration option to live in the recipe file.  Are there actually circumstances where you would mix both options in the same factory plan?

**Comment by Zistack** [comment]
I like the changes in your last two commits.  The only change I would make is to make 'net power consumption' the field that is only present when the factory produces power, and make `power consumption' the field that is unconditionally present.  I think if you make a PR with just those changes, I could merge it no problem.

I still have to work on building proper machine configuration reporting machinery, since I solved the somersloop allocation problem differently than you did.

**Comment by SpexGuy** [comment]
Thanks for taking a look! I made the requested changes re: net_power_consumption and packaged the last two commits together in #8.

> Question: I had originally imagined that choosing between 'underclock one' and 'underclock uniform' would be done with a command-line switch as a global option for the solver on all recipes. You implemented it as a per-recipe configuration option to live in the recipe file. Are there actually circumstances where you would mix both options in the same factory plan?

I think you might have misunderstood, My changes display both underclock_one and underclock_uniform together in the output. The user can choose which one they want, but both are present. There is no per-recipe configuration. I wouldn't expect users to mix them, and in most cases underclock_one is the only reasonable option, but both are listed. That said, a command-line switch to pick one wouldn't be a bad idea.

> Also, it shouldn't be possible to adjust the clock speed of sink recipes at all. I'll have to look into that.

Yeah, that's an oddity with how I'm determining clock speed. I'm pretty much doing num_machines / ceil(num_machines), regardless of whether the machine is actually capable of being clocked. Sinks become a bit of a special case, because they can sink any kind of item as opposed to being constrained to one recipe. My code does not handle this special case correctly.

> my corner infrastructure was designed to be extended in a different way than what you have done. This will probably affect how reporting should be done as well.

I'm interested to see the direction you had in mind! I see you've pushed more changes, I'll read through those to see if they show it.

> If I could merge only pieces of your changes, I would. I am not exactly a git(hub) master, though, and I'm not even sure that it is possible to do this.

It's possible but might be more trouble than it's worth. With a set of changes this small, it's probably easier to copy and paste the pieces you want than to use git to integrate them.

**Comment by Zistack** [comment]
> I think you might have misunderstood, My changes display both underclock_one and underclock_uniform together in the output. The user can choose which one they want, but both are present. There is no per-recipe configuration. I wouldn't expect users to mix them, and in most cases underclock_one is the only reasonable option, but both are listed. That said, a command-line switch to pick one wouldn't be a bad idea.

I did misunderstand, then.  I am curious about one more thing, though.  Why do you say that "in most cases underclock_one is the only reasonable option"?  I was going to default to the underclock_uniform behavior - and that's actually what my code currently does (I haven't implemented this switch yet) - because it is the power-optimal configuration.  Is this merely a practical concern with very large numbers of machines, or is there some numerical issue that I've overlooked?

**Comment by SpexGuy** [comment]
I was worried about a numerical issue of sorts that happens with large numbers of machines, but after calculating it out it doesn't seem like an issue.

In normal play, you have numbers like 6.5 machines. Clocking each machine at 92.8572% is optimal for power reasons, and multiplying that back you get a total production of `0.928572*7=6.500004`. A small amount of error is introduced by rounding the overclock multiplier to 6 digits, but this error doesn't really matter with a small number of machines. The total power is that of 6.4 machines if one is underclocked, and that of 6.3468 machines if all are equally underclocked.

In very large builds though, I thought this error would start to matter. If you have 1000.5 machines, they should be overclocked to 99.9501% each. Multiplying that back through 1001 machines gives 1000.500501. The total power is that of 1000.4 machines with overclock one, and that of 1000.3398 machines underclocking all of them.

So I was wrong, you would need around 50,000 machines in one configuration for this error to start to matter, which is almost double the total number of machines for all recipes together in the_big_cheese.

**Comment by Zistack** [comment]
OK, that's interesting.  The reason that I round to 6 digits is also because that's what the game rounds to (well, 4 digits in-game, but that's because I'm shifting the decimal point by 2).

I guess I hadn't considered that the error might start to dominate with a large number of machines, what with the underclock setting approaching the intended clock speed and the accumulation of error on each machine.  That little analysis if yours is useful though.

Anyways, thanks for the contributions.  It's cool to have users, and cooler to have users who help make the tool better.  I know the produced_by and consumed_by reporting will actually probably save me a lot of time with site planning on the megafactory that I'm currently gearing up to build.

Ima close this particular pull request now, as all changes have either been merged, implemented in a different way, or are planning to be implemented in a different way.  I'll still add that flag, I think, as some people like the convenience of just underclocking one machine, even though it's not power-optimal.

**Pull request closed without merging**
